### ISSUE TITLE
Can't able to clone the repository 

### ISSUE THREAD

**Issue by Dipanita45** [GSSoC24/Hack-Web3Conf#261]
Please help me 
@GSS0C24

**Comment by aslams2020** [comment]
What issue are u getting? Share

**Comment by Dipanita45** [comment]
It is showing can't clone

**Comment by Dipanita45** [comment]
Please check

**Comment by Dipanita45** [comment]
This is showing sir

I have retryed many times please check and resolve the issue

I have registered for web 3
How to get 250 points on leaderboard sir

**Comment by aslams2020** [comment]
I cant see the screenshot. have you shared it?

**Comment by Dipanita45** [comment]
Yes I sent

**Comment by Dipanita45** [comment]
![WhatsApp Image 2024-11-05 at 08 06 46_9692854b](https://github.com/user-attachments/assets/bec29f5f-a31c-4bd8-b783-f808d01ce315)

**Comment by Dipanita45** [comment]
![Uploading WhatsApp Image 2024-11-06 at 21.28.57_1201befd.jpg…]()

**Comment by Dipanita45** [comment]
please check

**Comment by Dipanita45** [comment]
![Uploading Screenshot 2024-11-06 213329.png…]()

**Comment by Dipanita45** [comment]
Cloning into 'C:\Users\dipan\OneDrive\Desktop\Documents\Project3\Hack-Web3Conf\Hack-Web3Conf'...
remote: Enumerating objects: 1999, done.        
remote: Counting objects: 100% (1113/1113), done.        
remote: Compressing objects: 100% (780/780), done.        
remote: Total 1999 (delta 1018), reused 392 (delta 333), pack-reused 886 (from 1)        
Receiving objects: 100% (1999/1999), 55.69 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (1074/1074), done.
error: invalid path 'Submit/NANDAGOPAL-STORYLENS:AI IMAGE NARRATIVE-2024-3NOV.png'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Would you like to retry cloning Hack-Web3Conf ?

**Comment by Dipanita45** [comment]
This is showing
sir

**Comment by Dipanita45** [comment]
![image](https://github.com/user-attachments/assets/a0c22ba4-5d8d-47f8-ab45-ff23410c89c5)

**Comment by ashiii1** [comment]
If you are cloning To add your file follow this you can even do this using your mobile Just fork this and from your profile open your forked repo then open submit file add your file by clicking corner upload file button add your after open pull request and send pull request

**Comment by Dipanita45** [comment]
Thank you sir I have uploaded

**Comment by Dipanita45** [comment]
Please merge my pull request and label me

**Comment by Sayan-dev731** [comment]
It is mainly happening due to naming convention which is creating conflicts when cloning the repo, it can be fixed by typing 'git restore --source=HEAD :/' or deleting that file which is creating the conflicts, make sure to have the backup before doing any changes to the repo.
